### ISSUE TITLE
Gamme commerciale d'application transport

### ISSUE THREAD

**Issue by struct-it** [interbob/xsd#1]
**Cas d'utilisation**
Un système A émet et distribue une application transport vierge. Le système A informe le système B via un  message IBACDA (5G). Le client veut acheter un titre depuis le système B sans présenter son support. Le système B ne sait pas lui proposer les titres adaptés à son application, car il ne connait pas la gamme commercial de ce support.

**Comment by struct-it** [comment]
**Solution à investiguer**
Remonter l'élément **ContratApplication** de type **t_ContratApplication** dans **t_ApplicationInstalleeAbstraite**

**Comment by rcasteran** [comment]
**Solution investiguée**
Remonter l'élément ContratApplication de type t_ContratApplication dans t_ApplicationInstalleeAbstraite

**Impacts identifiés**
Apparition de l'élément ContratApplication après l'élément Support dans les messages suivants:
- 1A-IBLSLN 
- 4A-IBLSDC
- 4B-IBLSRF
- 4D-IBLSSC
- 5G-IBACDA
- 5H-IBACBA
- 5I - IBACCA

_Remarque : message 5A-IBACDC : aucun impact, l'élément ApplicationUtilisee étant de type t_Application_

**Comment by rcasteran** [comment]
**Décision du GT6**
Besoin mal exprimé initialement, modification abandonnée.
