### ISSUE TITLE
Nouvelle structure compteur - Intercode 2.2

### ISSUE THREAD

**Issue by struct-it** [interbob/xsd#3]
**Cas d'utilisation**
Un utilisateur achète trois carnets de 10 tickets. Il consomme une unité, donc il n'a plus que deux carnets remboursables.
Actuellement, le nombre de jetons est compté, soit 2*10.

**Proposition**
En plus d'avoir le nombre de jetons, il serait souhaitable d'avoir le nombre de contrats.

**Question**
Dans le cas d'utilisation, on peut considérer :
1. une vente de trois produits, donc un message InterBob 
2. trois ventes du même produit, donc trois messages InterBob différents.
La norme actuelle est basée sur le principe (2). Or introduire un nombre de contrats impliquerait le principe (1). Est-ce souhaitable ?

**Comment by JulienCrespin** [comment]
Après réflexion, on peut noter que la structure de la balise compteur peut permettre de gérer ce besoin. Il suffit pour cela de proposer un nouvel identifiant de compteur permettant de définir le nombre de carnets chargés.... A débattre.

**Comment by struct-it** [comment]
**Décision du GT6**
Pas d'impact sur la norme, en attente d'une nouvelle expression de besoin
